version: "3.9"

services:
  test_fastapi_ylab:
    container_name: test_fastapi_ylab
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:root@postgres_ylab:5432/ylab"
    command: pytest -rm
    volumes:
      - shared-volume:/app/generated_files
    networks:
      - ylab_network
    depends_on:
      postgres_ylab:
        condition: service_healthy


  postgres_ylab:
    container_name: postgres_ylab_test
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: "ylab"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGUSER: "postgres"
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ylab -h 0.0.0.0 -p 5432"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s


networks:
  ylab_network:
    name: ylab_network
volumes:
  postgres_data:
  shared-volume:

